apiVersion: v2
name: n8n
version: 0.8.0
appVersion: 0.210.0
type: application

description: A Kubernetes Helm chart for n8n a free and open fair-code licensed node based Workflow Automation Tool. Easily automate tasks across different services.
home: https://github.com/8gears/n8n-helm-chart
icon: https://avatars1.githubusercontent.com/u/45487711?s=200&v=4
keywords:
  - Workflow Automation
  - Workflow
  - iPaaS
  - integration-framework
  - low-code-plattform
  - low-code
sources:
  - https://github.com/n8n-io/n8n
  - https://n8n.io/
maintainers:
  - name: Vadim Bauer

dependencies:
  - name: redis
    version: 17.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Updated App Version to 0.210.0
    - kind: added
      description: Support for dedicated Workers and Webhooks Instances by Stefan Warnat aka @swarnat
      links:
        - name: GitHub PR
          url: https://github.com/8gears/n8n-helm-chart/pull/24
        - name: Stefan Warnat aka @swarnat
          url: https://github.com/swarnat
