apiVersion: v2
name: n8n
version: 0.22.0
appVersion: 1.30.0
type: application

description: "A Kubernetes Helm chart for n8n a free and open fair-code licensed node based Workflow Automation Tool. Easily automate tasks across different services."
home: https://github.com/8gears/n8n-helm-chart
icon: https://avatars1.githubusercontent.com/u/45487711?s=200&v=4
keywords:
  - Workflow Automation
  - Workflow
  - iPaaS
  - integration-framework
  - low-code-plattform
  - low-code
sources:
  - https://github.com/n8n-io/n8n
  - https://n8n.io/
maintainers:
  - name: Vadim Bauer

dependencies:
  - name: redis
    version: 18.6.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
annotations:
  artifacthub.io/prerelease: "true"
  # supported kinds are added, changed, deprecated, removed, fixed and security.
  artifacthub.io/changes: |
    - kind: changed 
      description: "Apply Security Context to all Pods"
      links:
        - name: "Related GitHub Issue"
            url: https://github.com/8gears/n8n-helm-chart/issues/71         
