{{- if .Values.scaling.webhook.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" . }}-webhook
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.scaling.webhook.count }}
  {{- end }}
  strategy:
    type: {{ .Values.deploymentStrategy.type }}
    {{- if eq .Values.deploymentStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ default "25%" .Values.deploymentStrategy.maxSurge  }}
      maxUnavailable: {{ default "25%" .Values.deploymentStrategy.maxUnavailable }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "n8n.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/type: webhooks
  template:
    metadata:
      annotations:
        checksum/config: {{ print .Values | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "n8n.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/type: webhooks
        {{- if .Values.podLabels }}
          {{ toYaml .Values.podLabels | nindent 8 }}
        {{- end }}

    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "n8n.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainers }}
      initContainers:
      {{ tpl (toYaml .Values.initContainers) . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["n8n"]
          args: ["webhook"]
          env:
            {{- include "n8n.deploymentPodEnvironments" . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ get .Values.config "port" | default 5678 }}
              protocol: TCP
          resources:
            {{- toYaml .Values.webhookResources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ if semverCompare ">=1.0" (.Values.image.tag | default .Chart.AppVersion) }}/home/node/.n8n{{ else }}/root/.n8n{{ end }}
            {{- if .Values.config }}
            - name: config-volume
              mountPath: /n8n-config
            {{- end }}
            {{- if or (.Values.secret) (.Values.existingSecret) }}
            - name: secret-volume
              mountPath: /n8n-secret
                {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: "data"
          {{ include "n8n.pvc" . }}
        {{- if .Values.config }}
        - name: config-volume
          configMap:
            name: {{ include "n8n.fullname" . }}
        {{- end }}
        {{- if or (.Values.secret) (.Values.existingSecret) }}
        - name: secret-volume
          secret:
            secretName: {{ if .Values.existingSecret }}{{ .Values.existingSecret }}{{ else }}{{ include "n8n.fullname" . }}{{ end }}
            items:
              - key: "secret.json"
                path: "secret.json"
        {{- end }}
{{- end }}
