{{/*
extraManifests.yaml creates Kubernetes resources from values provided in
.Values.extraManifests and .Values.extraTemplateManifests
*/}}

{{- define "extraManifests.metadata" -}}
metadata:
  labels:
    app: {{ template "n8n.name" . }}
    chart: {{ template "n8n.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}

{{- $metadata := fromYaml (include "extraManifests.metadata" .) -}}

{{- $resources := list -}}
{{- range .Values.extraManifests }}
  {{- if typeIs "string" . }}
    {{/* Handle multi-part YAML documents */}}
    {{- range . | splitList "---\n" }}
      {{- with . | fromYaml }}
        {{- $resources = append $resources . }}
      {{- end }}
    {{- end }}
  {{- else }}
    {{- $resources = append $resources . }}
  {{- end }}
{{- end }}

{{- $templates := list -}}
{{- range .Values.extraTemplateManifests }}
  {{/* Handle multi-part YAML documents */}}
  {{- range . | splitList "---\n" }}
    {{- if . | fromYaml }}
      {{- $templates = append $templates . }}
    {{- end }}
  {{- end }}
{{- end }}

{{- range $resources }}
---
{{ merge . $metadata | toYaml }}
{{- end }}

{{- range $templates }}
---
{{ merge (tpl . $ | fromYaml) $metadata | toYaml }}
{{- end }}
