{{- if .Values.route.enabled }}
{{- $fullName := include "n8n.fullname" . -}}
apiVersion: {{ .Values.route.apiVersion | default "gateway.networking.k8s.io/v1" }}
kind: {{ .Values.route.kind | default "HTTPRoute" }}
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    {{- with .Values.route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.route.hostnames }}
  hostnames:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    {{- if .Values.route.additionalRules }}
    {{- tpl (toYaml .Values.route.additionalRules) $ | nindent 4 }}
    {{- end }}
    - backendRefs:
        - name: {{ $fullName }}
          port: {{ $.Values.main.service.port | default 80  }}
      {{- with .Values.route.main.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.route.main.matches }}
      matches:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
    {{- if $.Values.webhook.enabled }}
    - backendRefs:
        - name: {{ $fullName }}-webhook
          port: {{ $.Values.webhook.service.port | default 80  }}
      {{- with .Values.route.webhook.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.route.webhook.matches }}
      matches:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
