{{- if .Values.mcp.secret }}
{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-mcp-secret
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "toEnvVars" (dict "values" .Values.mcp.secret "prefix" "" "isSecret" true) | nindent 4 }}

{{- end }}
{{- end }}
