{{- if .Values.mcp.enabled }}
{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}-mcp
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  {{- with .Values.mcp.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.mcp.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.mcp.service.port | default 80  }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "n8n.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/type: mcp
{{- end }}
{{- end }}
